(() => {
  'use strict';
  const state = { clients: new Map(), groups: [], streams: [], socket: null, requestId: 0, pending: new Map(), timers: new Map(), dialogClient: null, moveClient: null, lastRefresh: null };
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const rpc = (method, params = {}) => new Promise((resolve, reject) => { if (!state.socket || state.socket.readyState !== WebSocket.OPEN) return reject(new Error('offline')); const id = ++state.requestId; state.pending.set(id, {resolve, reject}); state.socket.send(JSON.stringify({id, jsonrpc:'2.0', method, params})); });
  const refreshStatus = () => { if (!state.socket || state.socket.readyState !== WebSocket.OPEN) return Promise.resolve(false); return rpc('Server.GetStatus').then(result => { update(result); return true; }).catch(error => { console.warn('Server.GetStatus', error); return false; }); };
  const send = (method, params) => rpc(method, params).then(result => { refreshStatus(); return result; }).catch(error => console.warn(method, error));
  const nameOf = client => client.config?.name || client.host?.name || client.host?.friendly_name || client.host?.mac || client.id;
  const streamName = stream => stream.properties?.name || stream.id;
  const iconFor = stream => { const text = streamName(stream).toLowerCase(); return text.includes('spotify') ? '♫' : text.includes('airplay') ? '◉' : text.includes('tcp') ? '⌁' : '◌'; };
  const zoneName = (group, index) => group.name && !/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(group.name) ? group.name : `Zone ${index + 1}`;

  function connect() { if (state.socket) state.socket.close(); const scheme = location.protocol === 'https:' ? 'wss:' : 'ws:'; state.socket = new WebSocket(`${scheme}//hss.local/control/ws`); state.socket.onopen = () => { $('connection').textContent = 'Connected'; $('connection').className = 'status online'; refreshStatus(); }; state.socket.onclose = () => { $('connection').textContent = 'Offline'; $('connection').className = 'status offline'; setTimeout(connect, 3000); }; state.socket.onerror = () => state.socket.close(); state.socket.onmessage = event => { const message = JSON.parse(event.data); const pending = state.pending.get(message.id); if (pending) { state.pending.delete(message.id); message.error ? pending.reject(message.error) : pending.resolve(message.result); } if (message.method === 'Server.OnUpdate') update(message.params); }; }
  function relativeRefreshTime() { if (!state.lastRefresh) return 'Noch nicht geladen'; const seconds = Math.max(0, Math.floor((Date.now() - state.lastRefresh) / 1000)); if (seconds < 10) return 'Vor wenigen Sekunden'; if (seconds < 60) return `Vor ${seconds} Sekunden`; const minutes = Math.floor(seconds / 60); if (minutes < 60) return `Vor ${minutes} ${minutes === 1 ? 'Minute' : 'Minuten'}`; const hours = Math.floor(minutes / 60); return `Vor ${hours} ${hours === 1 ? 'Stunde' : 'Stunden'}`; }
  function renderRefreshTime() { const label = $('last-refresh'); if (label) label.textContent = relativeRefreshTime(); }
  function update(result) { const server = result?.server || result; state.lastRefresh = Date.now(); state.groups = server?.groups || []; state.streams = server?.streams || []; state.clients.clear(); state.groups.forEach(group => (group.clients || []).forEach(client => state.clients.set(client.id, {...client, groupId: group.id}))); ensureDefaultGrouping(); render(); renderRefreshTime(); }
  function ensureDefaultGrouping() { if (!state.clients.size || localStorage.getItem('hss-default-grouping') || !state.groups.length) return; const clients = [...state.clients.keys()]; const target = state.groups.find(group => group.name === 'Default') || state.groups[0]; send('Group.SetClients', {id:target.id, clients}); if (target.name !== 'Default') send('Group.SetName', {id:target.id, name:'Default'}); localStorage.setItem('hss-default-grouping', '1'); }
  function clientControl(client) { const volume = client.config?.volume || {}; const percent = Math.round(volume.percent ?? 50); return `<article class="client-row ${client.connected ? '' : 'is-offline'}" draggable="true" data-id="${esc(client.id)}" title="Double-click for details"><span class="drag-handle" title="Drag to another zone">⠿</span><span class="speaker-dot"></span><div class="client-info"><strong>${esc(nameOf(client))}</strong><small>${client.connected ? 'Online' : 'Offline'} · Double-click to edit</small></div><label class="inline-volume"><span class="sr-only">Volume</span><input class="volume" type="range" min="0" max="100" value="${percent}"><output>${percent}%</output></label><button class="mute icon-action" aria-label="${volume.muted ? 'Unmute' : 'Mute'}">${volume.muted ? '🔇' : '🔊'}</button><button class="move-client icon-action" aria-label="Move ${esc(nameOf(client))}" title="Move speaker">↗</button></article>`; }
  function render() { $('groups').innerHTML = state.groups.length ? state.groups.map((group, index) => { const members = (group.clients || []).map(client => state.clients.get(client.id) || client); const displayName = zoneName(group, index); const avg = members.length ? Math.round(members.reduce((sum, client) => sum + Number(client.config?.volume?.percent ?? 50), 0) / members.length) : 0; const muted = members.length > 0 && members.every(client => client.config?.volume?.muted); return `<article class="zone-card" data-zone="${esc(group.id)}"><div class="zone-heading"><div><button class="zone-name" data-rename="${esc(group.id)}" title="Rename zone">${esc(displayName)} <span>✎</span></button><small>${members.length} speaker${members.length === 1 ? '' : 's'}</small></div></div><label class="source-select"><span>Source</span><select data-stream-group="${esc(group.id)}"><option value="">No source</option>${state.streams.map(stream => `<option value="${esc(stream.id)}" ${group.stream_id === stream.id ? 'selected' : ''}>${iconFor(stream)} ${esc(streamName(stream))}</option>`).join('')}</select></label><div class="master-control"><div class="master-label"><span>Master volume</span><output>${avg}%</output></div><input class="master-volume" type="range" min="0" max="100" value="${avg}" aria-label="${esc(displayName)} master volume"><button class="mute-zone ${muted ? 'active' : ''}" data-zone-mute="${esc(group.id)}">${muted ? '🔇 Muted' : '🔊 Mute zone'}</button></div><div class="zone-members" data-drop-zone="${esc(group.id)}"><div class="members-label">Speakers <span>Drag to move</span></div>${members.length ? members.map(clientControl).join('') : '<p class="drop-hint">Drop a speaker here</p>'}</div></article>`; }).join('') : '<p class="empty">Your speakers will appear in a Default zone.</p>'; $('stream-list').innerHTML = state.streams.length ? state.streams.map(stream => `<article class="stream-row"><span class="stream-icon">${iconFor(stream)}</span><div><strong>${esc(streamName(stream))}</strong><small>${esc(stream.uri.raw || stream.id)}</small></div></article>`).join('') : '<p class="empty">No streams configured.</p>'; }
  function setClientVolume(id, percent, muted = false) { const client = state.clients.get(id); if (client) { client.config = client.config || {}; client.config.volume = {...client.config.volume, percent, muted}; } send('Client.SetVolume', {id, volume:{percent, muted}}); }
  function debouncedVolume(id, percent) { clearTimeout(state.timers.get(id)); state.timers.set(id, setTimeout(() => setClientVolume(id, percent), 100)); }
  function debouncedZoneVolume(zoneId, percent) { clearTimeout(state.timers.get(`zone:${zoneId}`)); state.timers.set(`zone:${zoneId}`, setTimeout(() => { const group = state.groups.find(item => item.id === zoneId); (group?.clients || []).forEach(client => setClientVolume(client.id, percent)); }, 100)); }
  function assign(zoneId, clientId) { const target = state.groups.find(item => item.id === zoneId); if (!target || !clientId || (target.clients || []).some(client => client.id === clientId)) return; state.groups.filter(group => group.id !== zoneId && (group.clients || []).some(client => client.id === clientId)).forEach(group => send('Group.SetClients', {id:group.id, clients:(group.clients || []).map(client => client.id).filter(id => id !== clientId)})); send('Group.SetClients', {id:zoneId, clients:[...(target.clients || []).map(client => client.id), clientId]}); }
  function newZone(clientId, name = 'New zone') { if (!clientId) return; const currentGroup = state.groups.find(group => (group.clients || []).some(client => client.id === clientId)); if (!currentGroup?.id) { console.warn('Cannot create zone: client group is unknown', clientId); return; } const remainingClients = (currentGroup.clients || []).map(client => client.id).filter(id => id !== clientId); rpc('Group.SetClients', {id:currentGroup.id, clients:remainingClients}).then(() => refreshStatus()).then(refreshed => { if (!refreshed) return; const group = state.groups.find(item => (item.clients || []).some(client => client.id === clientId)); if (group?.id) return send('Group.SetName', {id:group.id, name:name.trim() || 'New zone'}); }).catch(error => console.warn('Group.SetClients', error)); }
  function openMove(client) { state.moveClient = client; $('move-title').textContent = `Choose a zone for ${nameOf(client)}.`; $('move-target').innerHTML = `${state.groups.map((group, index) => `<option value="${esc(group.id)}">${esc(zoneName(group, index))}</option>`).join('')}<option value="__new__">＋ Create a new zone</option>`; $('move-dialog').showModal(); }
  function openDetails(client) { state.dialogClient = client; $('speaker-title').textContent = nameOf(client); $('speaker-alias').value = client.config?.name || ''; $('speaker-details').innerHTML = `<dt>Client ID</dt><dd>${esc(client.id)}</dd><dt>Host</dt><dd>${esc(client.host?.name || client.host?.mac || 'Unknown')}</dd><dt>IP address</dt><dd>${esc(client.host?.ip || 'Unknown')}</dd><dt>Status</dt><dd>${client.connected ? 'Online' : 'Offline'}</dd><dt>Latency</dt><dd>${esc(client.config?.latency ?? 0)} ms</dd>`; $('speaker-dialog').showModal(); }

  document.querySelectorAll('.tab').forEach(tab => tab.addEventListener('click', () => { document.querySelectorAll('.tab').forEach(item => item.classList.toggle('active', item === tab)); document.querySelectorAll('.view').forEach(view => { const active = view.id === tab.dataset.tab; view.classList.toggle('active', active); view.hidden = !active; }); }));
  document.addEventListener('input', event => { if (event.target.matches('.volume')) { const row = event.target.closest('[data-id]'), percent = Number(event.target.value); row.querySelector('output').textContent = `${percent}%`; debouncedVolume(row.dataset.id, percent); } if (event.target.matches('.master-volume')) { const zone = event.target.closest('[data-zone]'), percent = Number(event.target.value); zone.querySelector('.master-label output').textContent = `${percent}%`; debouncedZoneVolume(zone.dataset.zone, percent); } });
  document.addEventListener('change', event => { if (event.target.matches('[data-stream-group]')) send('Group.SetStream', {id:event.target.dataset.streamGroup, stream_id:event.target.value}); });
  document.addEventListener('click', event => { const target = event.target; if (target.matches('.mute')) { const client = state.clients.get(target.closest('[data-id]').dataset.id), volume = client.config?.volume || {}; setClientVolume(client.id, volume.percent ?? 50, !volume.muted); } if (target.matches('.move-client')) { event.stopPropagation(); openMove(state.clients.get(target.closest('[data-id]').dataset.id)); } if (target.matches('[data-zone-mute]')) { const group = state.groups.find(item => item.id === target.dataset.zoneMute), muted = !(group.clients || []).every(client => state.clients.get(client.id)?.config?.volume?.muted); (group.clients || []).forEach(client => { const current = state.clients.get(client.id)?.config?.volume?.percent ?? 50; setClientVolume(client.id, current, muted); }); } if (target.matches('.zone-name')) { const group = state.groups.find(item => item.id === target.dataset.rename), name = prompt('Zone name', group?.name || 'Zone'); if (name?.trim()) send('Group.SetName', {id:group.id, name:name.trim()}); } });
  document.addEventListener('dblclick', event => { const row = event.target.closest('.client-row'); if (row) openDetails(state.clients.get(row.dataset.id)); });
  document.addEventListener('dragstart', event => { const row = event.target.closest('.client-row'); if (row) { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', row.dataset.id); } });
  document.addEventListener('dragover', event => { const drop = event.target.closest('[data-drop-zone], [data-new-zone-drop]'); if (drop) { event.preventDefault(); drop.classList.add('drag-over'); } });
  document.addEventListener('dragleave', event => { const drop = event.target.closest('[data-drop-zone], [data-new-zone-drop]'); if (drop) drop.classList.remove('drag-over'); });
  document.addEventListener('drop', event => { const drop = event.target.closest('[data-drop-zone], [data-new-zone-drop]'); if (!drop) return; event.preventDefault(); drop.classList.remove('drag-over'); const clientId = event.dataTransfer.getData('text/plain'); if (drop.dataset.newZoneDrop) { const name = prompt('Name for the new zone', 'New zone'); if (name?.trim()) newZone(clientId, name.trim()); } else assign(drop.dataset.dropZone, clientId); });
  $('speaker-form').addEventListener('submit', event => { event.preventDefault(); const client = state.dialogClient, name = $('speaker-alias').value.trim(); if (!client) return; client.config = client.config || {}; client.config.name = name; send('Client.SetName', {id:client.id, name}).then(() => { $('speaker-dialog').close(); render(); }); });
  $('move-form').addEventListener('submit', event => { event.preventDefault(); const client = state.moveClient, target = $('move-target').value; if (!client || !target) return; if (target === '__new__') newZone(client.id); else assign(target, client.id); $('move-dialog').close(); });
  $('refresh').onclick = () => { if (state.socket?.readyState === WebSocket.OPEN) refreshStatus(); else connect(); };
  if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
  connect();
})();